### ISSUE TITLE
Username format issues

### ISSUE THREAD

**Issue by bbzap** [galkan/crowbar#1]
Hi,

Great tool, love it.

Would be nice if you supported usernames in the domain\username format as well as usernames that contain a space. It appears that domain\username becomes domainusername unless you encapsulate it in single quote marks.

However in the brief testing I have performed here passing known good credentials in the domain\username format encapsulated with single quotes seems to always result in a 'No result is found error'.

As always - could be me being an idiot. Never discount that possibility!

**Comment by galkan** [comment]
Hi,

As you said if you use username which contains space, it cannot work properly. I have fixed this issue and some bugs. I have just releases a new version. Could you try this one ? if you have any feedback, please let me know. 

Thank you for your valuable support. Best regards.

**Comment by PowerPress** [comment]
This looks like a great tool, how does it compare to ncrack in speed when doing RDP? Additionally does this work with proxychains?

**Comment by galkan** [comment]
I am not sure whether the crowbar can work with proxychains or not, but i think it works. Because as far i know how proxychains works, the only thing which you need is the proxy like TOR or any other SOCKS and set the config file. After that you are able to run crowbar with proxychains.

I dont have any experiences about this issue. But if you have experience about this issue, please let me know.
