### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by fuuddanni** [galkan/crowbar#3]
Hello, I´ve Python Version 2.6 & 2.7 && ruby 1.9.3p551 (2014-11-13) [i386-mingw32] && perl 5, version 14, subversion 2 in Windows x64 installed. 
SSH-Putty-Version: plink: Release 0.63.

By running crowbar i´ll get a short error Message:
No module named Crypto.PublicKey

Then i´ve installed openvpn, but the same error. 

What does this errorMessage mean? How do i install the needed Dependencies in Windows x64?

Thx for your attention.

**Comment by galkan** [comment]
Hi

I dont have any experiences about the installing crowbar on windows bases system. But what i understand from the message,  Crypto.PublicKey python module must be installed in order to run crowbar without any problem.

You can use pip or download the needed module from this page https://pypi.python.org/pypi/pycrypto
